/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassesDeletadas;

//import lisa.Telas.*;
import javax.swing.JOptionPane;
import lisa.Modelo.beans.Bairro;
import lisa.Modelo.dao.BairroDao;

/**
 *
 * @author dyhalmeida
 */
public class TelaCadEndereco extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadEndereco
     */
    public TelaCadEndereco() {
        initComponents();
        
        BairroDao bairroDao = new BairroDao();
        
        for(Bairro bairro: bairroDao.pesquisarBairro()){
            cb_bairro_enderecoCad.addItem(bairro);
        }
    }

    
    public void cadastrarEndereco(){
        
        Endereco endereco = new Endereco();
        endereco.setId(jt_idEnderecoCad.getText());
        endereco.setLogradouro(jt_enderecoLogradouro.getText());
        //endereco.setNumero(jt_numero_enderecoCad.getText());
        
        //Na linha abaixo o objeto bairro recebe com casting o objeto selecionado no jComboBox
        Bairro bairro = (Bairro) cb_bairro_enderecoCad.getSelectedItem();
        endereco.setBairro(bairro.getId());
        
                
        if(endereco.verificarCamposEndereco() == false){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
        }else{
            
            EnderecoDao eDao = new EnderecoDao();
            boolean verificarSeCadastrou = eDao.cadastrarEndereco(endereco);
            if(verificarSeCadastrou){
                JOptionPane.showMessageDialog(null, "Endereço cadastrado com sucesso!");
                limparCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Não conseguimos cadastrar este endereço");
            }
        }
    }
    
    private void limparCampos(){
        jt_idEnderecoCad.setText(null);
        jt_enderecoLogradouro.setText(null);
        //jt_numero_enderecoCad.setText(null);
        cb_bairro_enderecoCad.setSelectedItem(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIconEndereco = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbn_titulo_enderecoCad = new javax.swing.JLabel();
        lb_id_enderecoCad = new javax.swing.JLabel();
        jt_idEnderecoCad = new javax.swing.JFormattedTextField();
        lbn_logradouro_enderecoCad = new javax.swing.JLabel();
        jt_enderecoLogradouro = new javax.swing.JTextField();
        cb_bairro_enderecoCad = new javax.swing.JComboBox<>();
        lbn_bairro_enderecoCad = new javax.swing.JLabel();
        lb_camposObrigatorioEndereco = new javax.swing.JLabel();
        btn_cancelarCadEndereco = new javax.swing.JButton();
        btn_cadastrarEndereco = new javax.swing.JButton();
        lbn_cidade_enderecoCad = new javax.swing.JLabel();
        cb_cidade_enderecoCad = new javax.swing.JComboBox<>();

        setIconifiable(true);
        setTitle("Cadastro de endereço");

        lbIconEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lisa/Imagens/bairro_img.png"))); // NOI18N

        lbn_titulo_enderecoCad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbn_titulo_enderecoCad.setText("Cadastro de endereço");

        lb_id_enderecoCad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_id_enderecoCad.setText("ID*");

        jt_idEnderecoCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbn_logradouro_enderecoCad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbn_logradouro_enderecoCad.setText("Logradouro*");

        jt_enderecoLogradouro.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        cb_bairro_enderecoCad.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lbn_bairro_enderecoCad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbn_bairro_enderecoCad.setText("Bairro*");

        lb_camposObrigatorioEndereco.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        lb_camposObrigatorioEndereco.setText("* campos obrigatórios");

        btn_cancelarCadEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lisa/Imagens/cancel_img.png"))); // NOI18N
        btn_cancelarCadEndereco.setText("Cancelar");
        btn_cancelarCadEndereco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cancelarCadEndereco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cancelarCadEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarCadEnderecoActionPerformed(evt);
            }
        });

        btn_cadastrarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lisa/Imagens/ok_img.png"))); // NOI18N
        btn_cadastrarEndereco.setText("Cadastrar");
        btn_cadastrarEndereco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cadastrarEndereco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cadastrarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarEnderecoActionPerformed(evt);
            }
        });

        lbn_cidade_enderecoCad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbn_cidade_enderecoCad.setText("Cidade*");

        cb_cidade_enderecoCad.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jt_enderecoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbn_logradouro_enderecoCad))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbn_bairro_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cb_bairro_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lb_id_enderecoCad)
                                                .addGap(4, 4, 4)
                                                .addComponent(jt_idEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbn_cidade_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb_cidade_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_cancelarCadEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cadastrarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIconEndereco)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbn_titulo_enderecoCad)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lb_camposObrigatorioEndereco)
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbn_titulo_enderecoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_camposObrigatorioEndereco)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIconEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_idEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_id_enderecoCad))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbn_logradouro_enderecoCad)
                        .addGap(3, 3, 3)
                        .addComponent(jt_enderecoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbn_bairro_enderecoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_bairro_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastrarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarCadEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbn_cidade_enderecoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_cidade_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setBounds(200, 30, 410, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarCadEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarCadEnderecoActionPerformed
        // Fechar janela cadastro de endereço
        //this.dispose();
    }//GEN-LAST:event_btn_cancelarCadEnderecoActionPerformed

    private void btn_cadastrarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarEnderecoActionPerformed
        // chamando método para cadastrar endereço
       // this.cadastrarEndereco();
    }//GEN-LAST:event_btn_cadastrarEnderecoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarEndereco;
    private javax.swing.JButton btn_cancelarCadEndereco;
    private javax.swing.JComboBox<Object> cb_bairro_enderecoCad;
    private javax.swing.JComboBox<Object> cb_cidade_enderecoCad;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jt_enderecoLogradouro;
    private javax.swing.JFormattedTextField jt_idEnderecoCad;
    private javax.swing.JLabel lbIconEndereco;
    private javax.swing.JLabel lb_camposObrigatorioEndereco;
    private javax.swing.JLabel lb_id_enderecoCad;
    private javax.swing.JLabel lbn_bairro_enderecoCad;
    private javax.swing.JLabel lbn_cidade_enderecoCad;
    private javax.swing.JLabel lbn_logradouro_enderecoCad;
    private javax.swing.JLabel lbn_titulo_enderecoCad;
    // End of variables declaration//GEN-END:variables
}
